### ISSUE TITLE
Hue stopped working

### ISSUE THREAD

**Issue by k3rst1n** [ChristopherRogers1991/mycroft-hue#30] opened 2019-09-23 13:40 UTC
Hi,

Not sure why but my Hue skill stopped working. It used to work fine and suddenly it stopped.

I can see the following errors in the log console:

Playing WAVE '/home/pi/mycroft-core/mycroft/res/snd/start_listening.wav' : Signed 16 bit Little Endian, Rate 48000 Hz, Stereo
 13:35:41.041 | INFO     |   718 | __main__:handle_record_begin:36 | Begin Recording...
 13:35:41.053 | INFO     |   712 | AlarmSkill | on started...
 13:35:41.056 | INFO     |   712 | VolumeSkill | MUTING!
 13:35:41.059 | INFO     |   712 | VolumeSkill | Volume before mute: 99
 13:35:41.059 | INFO     |   712 | VolumeSkill | 99
0
 13:35:43.429 | INFO     |   712 | AlarmSkill | on ended...
 13:35:43.418 | INFO     |   718 | __main__:handle_record_end:41 | End Recording...
 13:35:43.423 | INFO     |   718 | mycroft.session:get:74 | New Session Start: 3288bd62-f24f-4565-91f2-663012275be9
 13:35:43.434 | INFO     |   718 | __main__:handle_wakeword:57 | Wakeword Detected: hey ezra
 13:35:44.945 | INFO     |   718 | __main__:handle_utterance:62 | Utterance: ['turn off light']
99
 13:35:45.144 | ERROR    |   712 | mycroft.skills.mycroft_skill.mycroft_skill:on_error:724 | An error occurred while processing a request in Phillips Hue Skill
Traceback (most recent call last):
  File "/home/pi/mycroft-core/mycroft/skills/mycroft_skill/event_container.py", line 66, in wrapper
    handler(message)
  File "/opt/mycroft/skills/mycroft-hue.christopherrogers1991/__init__.py", line 70, in handler
    if message.type == 'ConnectLightsIntent' \
AttributeError: 'Message' object has no attribute 'type'
 13:36:07.182 | WARNING  |   712 | mycroft.skills.settings:_update_settings_meta:301 | DEPRECATION WARNING: The "color" attribute in the settingsmeta file is no longer supported.
 13:36:07.185 | WARNING  |   712 | mycroft.skills.settings:_update_settings_meta:301 | DEPRECATION WARNING: The "name" attribute in the settingsmeta file is no longer supported.
 13:36:07.682 | ERROR    |   712 | mycroft.skills.settings:_issue_api_call:310 | Failed to upload skill settings meta for @0f178fc7-66b0-42b8-849f-3735240e7ced|mycroft-hue
Traceback (most recent call last):
  File "/home/pi/mycroft-core/mycroft/skills/settings.py", line 307, in _issue_api_call
    self.api.upload_skill_metadata(self.settings_meta)
  File "/home/pi/mycroft-core/mycroft/api/__init__.py", line 382, in upload_skill_metadata
    "json": settings_meta
  File "/home/pi/mycroft-core/mycroft/api/__init__.py", line 69, in request
    return self.send(params)
  File "/home/pi/mycroft-core/mycroft/api/__init__.py", line 152, in send
    return self.get_response(response, no_refresh)
  File "/home/pi/mycroft-core/mycroft/api/__init__.py", line 174, in get_response
    raise HTTPError(data, response=response)
requests.exceptions.HTTPError: {'skillMetadata': {'sections': {'0': {'fields': {'0': {'value': ["Couldn't interpret 'False' as string."]}}}}}}
  ^--- NEWEST ---^

I'm using a Raspberry Pi 3 Model B+ with the PS eye microphone.

I'm quite new to this, apologies if I missed anything.

Any ideas what the problem could be?

Thanks!

**Comment by ChristopherRogers1991** [comment] 2019-09-24 18:33
From:
```
File "/opt/mycroft/skills/mycroft-hue.christopherrogers1991/*init*.py",
line 70, in handler
if message.type == 'ConnectLightsIntent'
AttributeError: 'Message' object has no attribute 'type'
```

It looks like the Mycroft API has changed, and message no longer has a
type. Did you recently upgraded your Mycroft install? What version are you
running?

I am unable to do any dev work on this for the next two weeks,
unfortunately, so assuming it is that they have changed the API, I will not
be able to update the plug-in for at least that long. If you can down-grade
your install to the previous version that worked, that may get you working
again in the short term.

-Chris

**Comment by ChristopherRogers1991** [comment] 2019-09-26 20:16
Based on
https://community.mycroft.ai/t/solved-openhab-skill-not-working-after-upgrade/7285
and similar threads, it looks like 19.08 did indeed have some breaking
changes, so if you're in the latest version, that seems likely the cause.
I'll try to update the skill set some point, but for now, downgrading
mycroft is probably the only work around.

**Comment by k3rst1n** [comment] 2019-10-01 08:48
Hi Christopher,

thanks for looking into this. I'll downgrade whenever I get a chance.

Thanks,
Kerstin

**Comment by ChristopherRogers1991** [comment] 2019-10-26 12:35
With https://github.com/ChristopherRogers1991/mycroft-hue/commit/1c1eac8fd0169fa53f1736fcc33f127672b96149, this skill should work with the latest version of mycroft (19.08.2). If you pull down the latest changes to this skill and upgrade mycroft again, you should be all set. I'm going to go ahead and close this out, but please feel free to leave a comment if it's still not working for you.

-Chris

**Closed by ChristopherRogers1991** 2019-10-26 12:35 UTC
